checkpoint: checkpoints/1d_trinormal.ckpt
out_file: ../likelihood_results/trinormal_1d_nll_interp_diffspace_1000_take2.csv
sigma_min: 0.1
sigma_max: 30
data_samples: ../sample_results/trinormal_1d_1000.csv
trajectory_index_file: ../sample_results/trinormal_1d_traj/trajectory_index_1000.txt
inference_type: DiffSpaceIntegral
tr_type: non_conservative
diffusion_steps: 1000
odeint_rtol: 1e-5
odeint_atol: 1e-5
odeint_method: rk4
ode_steps: 200
num_workers: 4

interpolate_trajectories: True
num_interpolants: 10