# @package _global_
checkpoint: checkpoints/1d_trinormal_smax30_unnoised/weights.ckpt
out_dir: results/likelihood/noise_schedule_tests/gaussian_1d_diff_smax30
sigma_min: 0.1
sigma_max: 30
clamp_diffusion_coefficient: False
data_samples: results/sample_results/gaussian_1d_smax30/samples.csv
trajectory_index_file: results/sample_results/gaussian_1d_smax30/trajectories/trajectory_index.csv

tr_type: non_conservative

integrand_types:
  TotalIntegrand:
  FlowIntegrand:
prior_fns:
  smax_gaussian
  convolved_data
path_type: sde_trajectories

integral_type: 'diff'

integration:
  method: trapezoid

save_trajectories: False

batched: True
batch_size: 64