# @package _global_
checkpoint: checkpoints/1d_trinormal_smax30/weights.ckpt
out_dir: results/likelihood/noise_schedule_tests/gaussian_1d_still_smax30
sigma_min: 0.1
sigma_max: 30
clamp_diffusion_coefficient: False
data_samples: results/sample_results/gaussian_1d_smax30/samples.csv

tr_type: non_conservative

integrand_types:
  TotalIntegrand:
  FlowIntegrand:
prior_fns:
  smax_gaussian:
  convolved_data:
  estimated_data:
    data_variance: 898.532

path_type: still

integral_type: 'ode'
ode_steps: 100

integration:
  method: rk4
  rtol: 1e-5
  atol: 1e-5

save_trajectories: True

batched: True
batch_size: 64