checkpoint: checkpoints/dfmdock_model_0.ckpt
out_dir: ../likelihood_results/likelihoodv3/dfmdock_tr_2SIC_3integrand_diff
sigma_min: 0.1
sigma_max: 30
clamp_diffusion_coefficient: False
pdb_dir: ../sample_results/dfmdock_tr_2SIC/pdb
data_samples: ../sample_results/dfmdock_tr_2SIC/samples.csv
trajectory_dir: ../sample_results/dfmdock_tr_2SIC/trajectories
trajectory_index_file: ../sample_results/dfmdock_tr_2SIC/trajectories/trajectory_index.csv

integrand_types:
  TotalIntegrand:
  TimeIntegrand:
  SpaceIntegrand:
prior_fns:
  smax_gaussian
path_type: sde_trajectories

integral_type: 'diff'

tr_type: non_conservative

odeint_rtol: 1e-4
odeint_atol: 1e-4
odeint_method: rk4
ode_steps: 100
num_workers: 4

save_trajectories: True
save_trajectory_likelihoods: True

reset_seed_each_sample: True
seed: 0