# @package _global_
checkpoint: checkpoints/1d_trinormal_smax70.ckpt
out_dir: ../likelihood_results/likelihoodv3/gaussian_1d/ground_truth/3integrand_10ensembled_forward_sde_trapezoidint
sigma_min: 0.1
sigma_max: 70
clamp_diffusion_coefficient: False
data_samples: ../sample_results/trinormal_1d_smax70.csv
trajectory_index_file: ../sample_results/trinormal_1d_smax70_traj/trajectory_index.csv

integrand_types:
  TotalIntegrand:
  TimeIntegrand:
  SpaceIntegrand:
prior_fns:
  smax_gaussian
  convolved_data

tr_type: ground_truth

path_type: ensembled_forward_sde
ensemble_num_paths: 10
sde_steps: 1000 #match reverse diffusion

integral_type: 'diff'
integration:
  method: 'trapezoid'

save_trajectories: True

device: cpu

batched: True
batch_size: 64