# @package _global_
checkpoint: checkpoints/1d_trinormal_smax70.ckpt
out_dir: ../likelihood_results/likelihoodv3/gaussian_1d/ground_truth/3integrand_diff_backwardint
sigma_min: 0.1
sigma_max: 70
clamp_diffusion_coefficient: False
data_samples: ../sample_results/trinormal_1d_smax70.csv
trajectory_index_file: ../sample_results/trinormal_1d_smax70_traj/trajectory_index.csv

integrand_types:
  TotalIntegrand:
  TimeIntegrand:
  SpaceIntegrand:
prior_fns:
  smax_gaussian
  convolved_data
path_type: sde_trajectories
integral_type: 'diff'

tr_type: ground_truth

integration:
  method: euler_backward

ode_steps: 100
num_workers: 4

save_trajectories: True

device: cpu

batched: True
batch_size: 64