# @package _global_
checkpoint: checkpoints/1d_trinormal_smax70/weights.ckpt
out_dir: results/likelihood/diff_integration_methods/gaussian_1d_diff_backward_euler_interpolated
sigma_min: 0.1
sigma_max: 70
clamp_diffusion_coefficient: False
data_samples: results/sample_results/gaussian_1d/samples.csv
trajectory_index_file: results/sample_results/gaussian_1d/trajectories/trajectory_index.csv

tr_type: non_conservative

integrand_types:
  TotalIntegrand:
  FlowIntegrand:
prior_fns:
  smax_gaussian
  convolved_data
path_type: sde_trajectories

integral_type: piecewise_diff #divide the SDE path into a set of linear segments
piecewise_interpolants: 10 # each SDE step becomes 10 steps (e.g. 9 extra points per step)
integration:
  method: euler_backward

save_trajectories: False

batched: True
batch_size: 64