# @package _global_
checkpoint: checkpoints/diffenergy_tr_0.ckpt
out_dir: ../likelihood_results/likelihoodv3/dfmdock_trtrained_deterministic/oldsamples/3integrand_traj_flow_40
sigma_min: 0.1
sigma_max: 30
clamp_diffusion_coefficient: False
pdb_dir: ../sample_results/dfmdock_tr/pdb
# data_samples: ../sample_results/dfmdock_tr/samples.csv
trajectory_dir: ../sample_results/dfmdock_tr/trajectories
trajectory_index_file: ../sample_results/dfmdock_tr/trajectories/trajectory_index_singles.csv

offset_type: "Translation"

integrand_types:
  TotalIntegrand:
  TimeIntegrand:
  SpaceIntegrand:
prior_fns:
  smax_gaussian
path_type: flow_along_trajectory

integral_type: ode

tr_type: non_conservative

odeint_rtol: 1e-4
odeint_atol: 1e-4
odeint_method: rk4
ode_steps: 40
num_workers: 4

save_trajectories: True
save_trajectory_likelihoods: True

deterministic_score: True