# @package _global_
checkpoint: checkpoints/diffenergy_tr_0.ckpt
out_dir: results/likelihood/dfmdock_gt_forwardsde_ensembled
sigma_min: 0.1
sigma_max: 30
clamp_diffusion_coefficient: False
pdb_dir: db5_test
data_samples: db5_test/index.csv

offset_type: "Translation"
tr_type: non_conservative

integrand_types:
  TotalIntegrand:
  FlowIntegrand:
prior_fns:
  smax_gaussian
  receptor_smax_gaussian

path_type: forward_sde
sde_steps: 40
integral_type: 'diff'
num_replicates: 15

integration:
  method: trapezoid

save_trajectories: True
save_trajectory_likelihoods: True

deterministic_score: True

