# @package _global_
checkpoint: checkpoints/diffenergy_tr_0.ckpt
out_dir: results/forces/dfmdock
sigma_min: 0.1
sigma_max: 30
clamp_diffusion_coefficient: False
pdb_dir: results/sample_results/dfmdock/pdb
trajectory_dir: results/sample_results/dfmdock/trajectories
trajectory_index_file: selected_dfmdock_trajectories.csv

offset_type: "Translation"
tr_type: non_conservative

path_type: sde_trajectories

deterministic_score: True