# @package _global_
checkpoint: checkpoints/1d_trinormal_smax70_unnoised.ckpt
out_dir: ../testconf/likelihood/gaussian_1d_diff
sigma_min: 0.1
sigma_max: 70
clamp_diffusion_coefficient: False
data_samples: ../sample_results/trinormal_1d_smax70_unnoised/samples.csv
trajectory_index_file: ../sample_results/trinormal_1d_smax70_unnoised/trajectories/trajectory_index.csv

integrand_types:
  TotalIntegrand:
  TimeIntegrand:
  SpaceIntegrand:
prior_fns:
  smax_gaussian
  convolved_data
path_type: sde_trajectories

integral_type: 'diff'

tr_type: non_conservative

integration:
  method: trapezoid

ode_steps: 100
num_workers: 4

save_trajectories: False

batched: True
batch_size: 64