checkpoint: ../checkpoints/dfmdock_model_0.ckpt
out_file: ../../results/dfmdock_tr_flowtime_nll.csv
sigma_min: 0.1
sigma_max: 30
data_directory: ../../data/pdbs
data_listpdb: ../../data/pdb_list.txt
inference_type: FlowTimeIntegral
diffusion_steps: 40
odeint_rtol: 1e-4
odeint_atol: 1e-4
odeint_method: rk4
ode_steps: 100
num_workers: 6
reset_seed_each_sample: True
seed: 0
