out_dir: ../sample_results_refactor/trinormal_1d_smax70_unnoised
wt_file: checkpoints/1d_trinormal_smax70_unnoised.ckpt
# sample_file: trinormal_1d_smax70.csv
sample_num: 10000
tr_type: non_conservative
num_steps: 1000
sigma_min: 0.1
sigma_max: 70
save_trajectory: True
batched: True
trajectory_extra_indices: [1000,25]
batch_size: 1000