out_dir: ../sample_results
wt_file: checkpoints/2d_trinormal.ckpt
sample_file: trinormal_2d.csv
sample_num: 10000
tr_type: non_conservative
num_steps: 1000
sigma_min: 0.1
sigma_max: 30
save_trajectory: True
